### PR TITLE
fix pagination on mobile screen

### LINKED ISSUE #1: Bug: Make the Pagination responsive for  Mobile devices

### PR DESCRIPTION
**Pull request by tan911**
This fix #1 enables pagination on mobile screen. Some changes is not directly related to problem but on prettier, the way my configuration in my vscode will automatically format the text.

### CODE REVIEW

**Comment by RajeevDash007** [comment]
> This fix enables pagination on mobile screen. Some changes is not directly related to problem but on prettier, the way my configuration in my vscode will automatically format the text.

Great!!
GSoC-Github-Finder
now the pagination looks something like this in mobile,
dont you think that it will look better if you can change the layout of the pagination in mobile like:
(previous   1 of 22   next) rather than (previous   next    1 of 22)

you can make changes and commit your changes

**Comment by tan911** [comment]
> > This fix enables pagination on mobile screen. Some changes is not directly related to problem but on prettier, the way my configuration in my vscode will automatically format the text.
> 
> Great!! GSoC-Github-Finder now the pagination looks something like this in mobile, dont you think that it will look better if you can change the layout of the pagination in mobile like: (previous 1 of 22 next) rather than (previous next 1 of 22)
> 
> you can make changes and commit your changes

Yeah, I try that looks for the library you use but when I started to hide everything inside next/prev it also hide entire pagination. Or  I might be missing something on documentation.

**Comment by tan911** [comment]
Oh, there's actually a workaround to achieve that looks,
But there's also bugs right now in pagination so here's the picture of it

image

**Comment by RajeevDash007** [comment]
> Oh, there's actually a workaround to achieve that looks, But there's also bugs right now in pagination so here's the picture of it
> 
> image

thats great,
so we need to remove that "of 227" in the mobile view,
can you fix it?

**Comment by tan911** [comment]
> > Oh, there's actually a workaround to achieve that looks, But there's also bugs right now in pagination so here's the picture of it
> > image
> 
> thats great, so we need to remove that "of 227" in the mobile view, can you fix it?

Yeah, but I don't know how to fix it, In react-paginate that's actually how the pagination works. I mean it really has that duplication on labels when  the current page(number) is in the middle of total page.


Here's how to add that label

image

now if you remove that breakLabel props it fall to default which is the elipsis(with 3 dots).
and since we are in the current page the elipsis now doubled

image

**Comment by RajeevDash007** [comment]
> > > Oh, there's actually a workaround to achieve that looks, But there's also bugs right now in pagination so here's the picture of it
> > > image
> > 
> > 
> > thats great, so we need to remove that "of 227" in the mobile view, can you fix it?
> 
> Yeah, but I don't know how to fix it, In react-paginate that's actually how the pagination works. I mean it really has that duplication on labels when the current page(number) is in the middle of total page.
> 
> Here's how to add that label
> 
> image
> 
> now if you remove that breakLabel props it fall to default which is the elipsis(with 3 dots). and since we are in the current page the elipsis now doubled
> 
> image

Okay , 
there is a library called "react-responsive-pagination", Ig it will solve the problem.
would you like to work on it?

**Comment by tan911** [comment]
> > > > Oh, there's actually a workaround to achieve that looks, But there's also bugs right now in pagination so here's the picture of it
> > > > image
> > > 
> > > 
> > > thats great, so we need to remove that "of 227" in the mobile view, can you fix it?
> > 
> > 
> > Yeah, but I don't know how to fix it, In react-paginate that's actually how the pagination works. I mean it really has that duplication on labels when the current page(number) is in the middle of total page.
> > Here's how to add that label
> > image
> > now if you remove that breakLabel props it fall to default which is the elipsis(with 3 dots). and since we are in the current page the elipsis now doubled
> > image
> 
> Okay , there is a library called "react-responsive-pagination", Ig it will solve the problem. would you like to work on it?

Sure, I will try to work on it tomorrow and I'll open a PR right after when everything is good. Thanks.

**Comment by RajeevDash007** [comment]
@tan911 you need to pull all changes,
then resolve the conflicts to get your PR merged

**Comment by RajeevDash007** [comment]
I am closing this PR, as another PR has been raised of same issue

**Pull request closed without merging**
